### ISSUE TITLE
Issues with Nested Flow

### ISSUE THREAD

**Issue by michaelmarcuccio** [joel-wenzel/ng-flowchart#18]
If you try to drag the nested flow and drop it onto itself it throws error.
If you try to drag existing step on canvas onto the nested flow it throws error.

![image](https://user-images.githubusercontent.com/20432260/130529360-623dacee-750a-4d05-869d-40f902ff99ca.png)

**Comment by joel-wenzel** [comment]
@michaelmarcuccio To be honest I do not like the nested flow at all. It was introduced to allow parallel lanes to converge on a single child. I am making more fundamental changes to allow this behavior. Is this the purpose you are trying to use the nested flow?

**Comment by michaelmarcuccio** [comment]
yeah pretty much, but I would also like to be able to have a list of pre-existing flowcharts in my palette menu and be able to drag them into a flowchart as a nested flow. Essentially a flowchart template step that pulls in multiple steps as a big group from a previously created flowchart. I haven't tried this yet, so I don't know if this is currently possible or not, though. There may be better options than what I mentioned for the same functionality.

**Comment by joel-wenzel** [comment]
@michaelmarcuccio Got it. Sounds like a nested flow would actually be the right approach based on the use case you described. I will take a look at this tomorrow then.

**Comment by joel-wenzel** [comment]
@michaelmarcuccio I spent a while looking at this and it became too complicated to move steps between canvases so for now I wont be fixing this in the current model. I will keep your use case in mind during the v2 release as things get reworked however.

**Comment by michaelmarcuccio** [comment]
Is there a way to prevent moving steps into the nested flow/moving the nested flow into itself? The bug occurs before the "canDrop()" method, so I cannot prevent drops on the flow. I do not necessarily want the capability to move steps between canvases, just want to stop the ability of accidentally trying to thus causing an error.

Although, if you think the nested flow implementation will be replaced that is fine too. Just trying to give you some bug info.

**Comment by joel-wenzel** [comment]
I actually did push a change that prevents the error and wont let you drop into a nested canvas. This should be in beta version 1.0.0-beta.4

**Comment by michaelmarcuccio** [comment]
Sorry to bring this up again, but now after using nested flows for looping, we tend to have pretty much every step in a flow in or around a nested flow. Not being able to drag steps between normal canvas to nested canvas and vice versa is pretty rough on the user experience. Do you think this is possible to implement with the current design of everything? I could potentially work on implementing this in the library if I can get some extra time soon and wondering if you had any info on this as you looked into it earlier.
