### ISSUE TITLE
Horizontal Layout option on Tree flow

### ISSUE THREAD

**Issue by joel-wenzel** [joel-wenzel/ng-flowchart#19]

**Comment by davidlepon** [comment]
hey, is there a chance that it will be implemented soon?

thanks in advance

**Comment by GouthamHarshith1997** [comment]
Hi Joel, I am looking for this enhancement, is there any chance that it will be implemented?

**Comment by ashutoshAgreeya** [comment]
Hello Joel, Looking for this feature, Is there any chance to release it ?
