### ISSUE TITLE
Horizontal step overflow issue

### ISSUE THREAD

**Issue by michaelmarcuccio** [joel-wenzel/ng-flowchart#20]
![image](https://user-images.githubusercontent.com/20432260/130541792-63ef257b-6e9d-4136-8160-5aca7ca684a4.png)

If you add a bunch of steps that overflows horizontally, the 'left' attribute is in the negatives and you cannot scroll to see those steps. 

![image](https://user-images.githubusercontent.com/20432260/130542393-48f18194-4578-4b5a-a64e-31870da265fc.png)

Was the scroll zoom meant to be a partial resolution to this? I disabled scroll zoom in my implementation as I want the canvas to scroll instead of zooming.

**Comment by joel-wenzel** [comment]
@michaelmarcuccio Should be fixed in the latest version 1.0.0-beta.3
