### ISSUE TITLE
move error

### ISSUE THREAD

**Issue by Jack724** [joel-wenzel/ng-flowchart#24]
1. try move child node to the top of root node
2. move nodes and will stuck

**Comment by joel-wenzel** [comment]
@Jack724 What version are you using? This issue was fixed in 1.0.0-beta.5

**Comment by michaelmarcuccio** [comment]
[https://stackblitz.com/edit/ng-flowchart-nested-q7u1hc?file=src/app/nested-flow/nested-flow.component.ts](https://stackblitz.com/edit/ng-flowchart-nested-q7u1hc?file=src/app/nested-flow/nested-flow.component.ts)

![image](https://user-images.githubusercontent.com/20432260/132595610-0c4c734e-4a2e-4358-a862-c191d932dae4.png)


If you drag the child item above the root item it has infinite recursion.
Edit: confusing example

**Comment by joel-wenzel** [comment]
@michaelmarcuccio @Jack724 Do you want to give version **1.0.0-beta.7** a try?

**Comment by michaelmarcuccio** [comment]
Looks good. Tested everything I could and it was smooth.

**Comment by michaelmarcuccio** [comment]
this created a new issue when adding a step above a step that had adjacent steps
