### ISSUE TITLE
Nested flow auto-resize

### ISSUE THREAD

**Issue by michaelmarcuccio** [joel-wenzel/ng-flowchart#25]
In v1.0.2-beta, the auto-resize of the nested flow functionality was either removed or broken by the new zoom functionality.

Working v1.0.0-beta: [https://stackblitz.com/edit/ng-flowchart-nested?file=src/app/nested-flow/nested-flow.component.ts](https://stackblitz.com/edit/ng-flowchart-nested?file=src/app/nested-flow/nested-flow.component.ts)
Not Working v1.0.2-beta: [https://stackblitz.com/edit/ng-flowchart-nested-xsysul?file=src/app/nested-flow/nested-flow.component.ts](https://stackblitz.com/edit/ng-flowchart-nested-xsysul?file=src/app/nested-flow/nested-flow.component.ts)

Was this removed due to the new implementation of zoom? I was trying to restore the auto resize nested flow functionality but was having some trouble getting it to work due to all the manual calculation that goes on in the rendering.

**Comment by joel-wenzel** [comment]
@michaelmarcuccio This was removed when zoom was added. Zoom felt more intuitive. I can add this functionality back if zoom is disabled though.

**Comment by michaelmarcuccio** [comment]
![image](https://user-images.githubusercontent.com/20432260/132596166-cb4d4811-4f3a-4a97-99fe-4a3565685d79.png)

Zoom is really unfriendly in these nested flow scenarios from what I can see. Having the nested flow fit to its content or slightly larger gives it a more nested/wrapped feeling in my opinion. If I do enable zoom it would only be on the main flow and the nested flow would be disabled, and when you zoom the main flow, the nested flow adjusts based off content. It would be great to have both options I guess.

This brings up another point which might be the reason the zoom doesn't feel right. If you have WHEEL enabled on main flow and nested flow and you try to WHEEL zoom the nested flow, both the main and nested flow change zoom.

**Comment by joel-wenzel** [comment]
Got it. In the meantime I added the auto resize back but only when zoom is disabled. Version 1.0.0-beta.7

**Comment by michaelmarcuccio** [comment]
The nested flow doesn't recalculate size when removing steps from the nested flow. I can look into this later if you don't already know the solution. I was hoping for the nested flow to follow the size of its contents shrinking or growing.

Also, I think this caused another bug for any flow(not just nested) where the 'ngflowchart-canvas-content' min-width & min-height do not get recalculated when removing steps. This keeps the canvas huge even if you remove all the steps and is quite a problem.

EDIT: I just confirmed the bug does not occur in 1.0.0-beta.6 but does now occur in 1.0.0-beta.7.
