### ISSUE TITLE
Hi , could you please upload a demo code source for readers

### ISSUE THREAD

**Issue by HePeng11** [joel-wenzel/ng-flowchart#3]
Hi , could you please upload a demo code source for readers, I even can't create a simple demo according to the description on this page . tks a lot

**Comment by joel-wenzel** [comment]
Hello, the repository itself is a sandbox more or less for the flowchart library. You can just clone this repository and run it to see an example.
```
git clone https://github.com/joel-wenzel/ng-flowchart.git
cd ng-flowchart
npm i
npm run start
```
There will be more up to date stackblitz links at some point.

**Comment by HePeng11** [comment]
hi joel, tks your remind, I can see the exaple now, it's a good and high quantity project but seems just support parent-children-children format data structure, not meet my need , it's better if can draw a workflow arbitrarily like this gooflow, thks your help anyway~
![image](https://user-images.githubusercontent.com/23466980/111862600-3953f980-8991-11eb-9eba-c3b30e2c174a.png)
