### ISSUE TITLE
Options not accessible to nested flow

### ISSUE THREAD

**Issue by michaelmarcuccio** [joel-wenzel/ng-flowchart#30]
I cannot pass the parent canvas NgFlowchart.Options to the child canvas. 

```
<div class="nested-flow-step" #canvasContent>
  <div
    ngFlowchartCanvas
    [ngFlowchartOptions]="canvas.options" // this canvas.options is private
    [ngFlowchartCallbacks]="callbacks"
    class="nested-canvas-content"
    [disabled]="canvas.disabled"
  ></div>
</div>
```

Additionally, the OptionsService is also not possible to share between parent and child canvas in an external project.
Example here trying to propagate the service reference into nested component.

package can't be found from:
import { OptionsService } from '@joelwenzel/ng-flowchart/lib/services/options.service';
[https://stackblitz.com/edit/ng-flowchart-nested-hg6wfd?file=src%2Fapp%2Fnested-flow%2Fnested-flow.component.ts](https://stackblitz.com/edit/ng-flowchart-nested-hg6wfd?file=src%2Fapp%2Fnested-flow%2Fnested-flow.component.ts)

**Comment by joel-wenzel** [comment]
@michaelmarcuccio I believe this should be fixed in version `1.0.0-beta.10` 
I was having weird issues in stackblitz updating the dependency but I am fairly confident its just a stackblitz issue.

**Comment by michaelmarcuccio** [comment]
@joel-wenzel stackblitz does seem to have a package issue with ng-flowchart. I couldn't get it to go to 1.0.0-beta.9 earlier as well.
I tried these changes in my project and it did not work. 

```
@Component({
  selector: 'app-nested-flow',
  templateUrl: './nested-flow.component.html',
  styleUrls: ['./nested-flow.component.scss'],
  providers: [OptionsService]
})

constructor(
    private optionsService: OptionsService
  ) {
    super();
  }
```
Error: Module not found: Error: Can't resolve '@joelwenzel/ng-flowchart/lib/services/options.service'.
It has trouble injecting the service, not sure if this is intended or not.
Also, the options property needs to be public from the NgFlowchartCanvasService not the NgFlowchartCanvasDirective to be able to access the parent canvas options in the nested flow template. I may be missing something, though, just let me know.

**Comment by joel-wenzel** [comment]
You are right on the canvas directive/service issue.  I will update that. The options service inject should work though. Try changing your import from `@joelwenzel/ng-flowchart/lib/services/options.service` to just the standard `@joelwenzel/ng-flowchart`

Note that if the intent is to share the same options service across all canvases you would want to only provide the service in the base canvas component. I can create a stackblitz (or at least try to) if needed

**Comment by joel-wenzel** [comment]
@michaelmarcuccio Actually let me know if changing the import does what you are looking for. I would rather leave the options service private on the canvas. I am open to making it public but only if other avenues don't pan out.

**Comment by michaelmarcuccio** [comment]
Yep, the options service works for this specific case. I just have the option service provided at the very base level and inject it into nested canvas constructors. In the base component I do optionsService.setOptions(options), while also manually setting the base canvas  [ngFlowchartOptions]="options". It all works from there. You can close this issue if you want.
