### ISSUE TITLE
Callbacks: onDeleteStep

### ISSUE THREAD

**Issue by michaelmarcuccio** [joel-wenzel/ng-flowchart#32]
Is there a potential to have a callback for steps being deleted in a canvas?
I think it is needed for many cases where a step is deleted anywhere in the canvas and you want to trigger something.
It seems to fit well in the list of callbacks:
  add/move
  +delete
  render
  scale

**Comment by joel-wenzel** [comment]
@michaelmarcuccio Yep. I like that idea. I will add that today or tomorrow.

**Comment by joel-wenzel** [comment]
```beforeDeleteStep``` and ```afterDeleteStep``` should be added now in version ```1.0.0-beta.11```. As part of this change I also made canvas.options public :)
