### ISSUE TITLE
Nested-flow

### ISSUE THREAD

**Issue by HyperZed** [joel-wenzel/ng-flowchart#35]
Hi Joel,

I don't know how to remove a step that has been inserted inside a nested flow, because we cannot access the internal flow from the outside.

Attached the image of the interface created.

Thanks in advance.
![Screenshot (8)](https://user-images.githubusercontent.com/66058958/137449019-f27d33bd-b9e9-4226-a686-5e1a3424bf75.png)

**Comment by michaelmarcuccio** [comment]
You use your 'PLUG-IN' step component instance and step.destroy()

**Comment by HyperZed** [comment]
this.canvas.getFlow().getStep(id).destroy(false);

I use this to delete but I can't delete the steps inside the nested component.

https://stackblitz.com/edit/ng-flowchart-nested?file=src/app/nested-flow/nested-flow.component.ts


also here in your stackbltiz the 'Logs' inside the nested cannot be deleted individually

**Comment by michaelmarcuccio** [comment]
If you need to use the canvas instance to delete steps(not sure why this would be done, but I am guessing there are use cases), then you need to get the nested step component instance to do nestedStepComponentInstance.nestedCanvas.getFlow() .....

**Comment by HyperZed** [comment]
Thanks for the response Michael,


I am trying to retrieve the instance, but cannot.
We tried with the Viewchild and Viewchildren directives, 
but despite the component being loaded into the DOM I can't get it back.
Is there a particular way to take the instance?

**Comment by michaelmarcuccio** [comment]
Yes, the nested step component is a step, so you can retrieve it by id just like you do the other steps.

If you just put the delete button in your step component, then it makes things a lot simpler.

**Comment by HyperZed** [comment]
Thanks, 
I'll try this solution. 
In the meantime I have handled it in another way.

thanks for the explanations.

Have a nice day.

Simone
