### ISSUE TITLE
NgIf Issue

### ISSUE THREAD

**Issue by tanishkab** [joel-wenzel/ng-flowchart#36]
I face issue when I use this using *ngIf , as when I use it conditionally it doesnt work properly , it lags until I scroll or do something on screen

**Comment by michaelmarcuccio** [comment]
It sounds like you need to trigger change detection, or maybe even rerender() canvas.

**Comment by joel-wenzel** [comment]
@tanishkab Can you also check if change detection is set to push in your component that has the canvas?

**Comment by tanishkab** [comment]
@michaelmarcuccio Yeah, I triggered change detection to solve this issue 
@joel-wenzel  No, it wasn't set to push.
