### ISSUE TITLE
creating loops

### ISSUE THREAD

**Issue by ing-fcastellanos** [joel-wenzel/ng-flowchart#37]
Hi @joel-wenzel, amazing work!! I was wondering if you could add loops on the flowchart for rework? Something like this:

![image](https://user-images.githubusercontent.com/55556753/149395671-0c2f1102-dc59-4ee2-a530-796cb06fb45d.png)

Thanks!

**Comment by michaelmarcuccio** [comment]
I implemented something that effectively allows you to loop.

![image](https://user-images.githubusercontent.com/20432260/149396923-05ca72a1-84db-4889-9717-ec637b9fcebe.png)

The entire group loops unless you select end repeat on a leaf step.
This was a way I imagined would work with the existing functionality of the flowchart code. But It complicates things a lot and wasn't as smooth as I wanted it to be.

**Comment by joel-wenzel** [comment]
@fcastellanosKreios Thank you. unfortunately looping is not possible unless you do something like @michaelmarcuccio highlighted. I am working on a second version library that would allow more robust features like that but it is slow going.

**Comment by ing-fcastellanos** [comment]
Thanks for the response. In the meantime I create a workaround for this, is a standardStep with a selector on the edit button in which a choose a previous step and save the ID in the config.

**Comment by saurabhmehta-me** [comment]
We also have a use case where a child can route the flow to an existing parent. I thought of a solution that there should be an option to add a Symbolic Node that is shown as a child node but it represents a parent above in the call flow. The symbolic node should be clickable and it should vertically scroll to the parent when clicked on the symbolic node
