### ISSUE TITLE
not enough space to add new item at the end of the page

### ISSUE THREAD

**Issue by hknsrr** [joel-wenzel/ng-flowchart#39]
How can we give some space to add a new item when we scroll to the end of the page?

![image](https://user-images.githubusercontent.com/10279164/154817076-9153a76e-67a5-4860-92ae-ddcf1193ed31.png)

Thank you.

**Comment by michaelmarcuccio** [comment]
I run into this a lot and I could not figure out how to resolve it when I was refactoring some of the rendering a few months ago. If anyone has any ideas that would be good.

**Comment by michaelmarcuccio** [comment]
If you drag a step to the very bottom it should add you some room: 
<img width="629" alt="Screenshot 2023-01-14 at 11 11 53 PM" src="https://user-images.githubusercontent.com/20432260/212523992-634dc374-2a52-42f5-b8c7-3590a30f7d94.png">
