### ISSUE TITLE
Error in tree mount

### ISSUE THREAD

**Issue by blzpedro** [joel-wenzel/ng-flowchart#4]
Hi, when i'm trying to mount tree with multiple nodes returns an error in console
![image](https://user-images.githubusercontent.com/33239399/121027905-b6fff800-c77d-11eb-8935-f2d750b44bab.png)

What i'm i doing wrong? And what can be the solution?

**Comment by blzpedro** [comment]
Solved.

If someone get this error, i think this happens(didn't know exactly why) cause width from canvas box is not compatible with width from all steps tree.

**Comment by joel-wenzel** [comment]
@blzpedro Thanks for finding. Can you elaborate on what you mean by not compatible?

**Comment by blzpedro** [comment]
Basically using css max-width/flex property in class **.ngflowchart-canvas-content** returns the error from printscreen and Chrome starts to crash.

**Comment by blzpedro** [comment]
> @blzpedro Thanks for finding. Can you elaborate on what you mean by not compatible?

Basically using css max-width/flex property in class .ngflowchart-canvas-content returns the error from printscreen and Chrome starts to crash.
