### ISSUE TITLE
after zooming, new item cannot be add even if the red mark appears

### ISSUE THREAD

**Issue by hknsrr** [joel-wenzel/ng-flowchart#40]
After zooming, it is absolutely necessary to drop it on the red dot in order to drop a new item. So, new item cannot be add even if the red mark appears.

![image](https://user-images.githubusercontent.com/10279164/154817176-78af51f4-e4c7-4833-a7e4-4088eb4c85d7.png)

**Comment by GouthamHarshith1997** [comment]
is this issue got solved already? when I am trying to add new element after zooming out, then the flow is getting scattered
