### ISSUE TITLE
Locking Root Step in Flow

### ISSUE THREAD

**Issue by donbwhite** [joel-wenzel/ng-flowchart#41]
I'm wondering if there's a way to "lock" the root step in the flow so that you can't add a step to the top of it. I might be missing something but not sure how to define available positions for steps.

**Comment by michaelmarcuccio** [comment]
custom-step.component.ts
```
// prevents you from dropping this step above a root step
  canDrop(dropEvent: NgFlowchart.DropTarget): boolean {
    if (dropEvent && !dropEvent.step.parent && dropEvent.position === 'ABOVE') {
      return false;
    }
    return true;
  }
```
