### ISSUE TITLE
How to pass a custom event from class CustomStepComponent that extends the NgFlowchartStepComponent

### ISSUE THREAD

**Issue by saurabhmehta-me** [joel-wenzel/ng-flowchart#43]
I have a requirement to output a custom event from class CustomStepComponent that extends the NgFlowchartStepComponent and catch the same in the <div id="canvas" ngFlowchartCanvas [ngFlowchartOptions]="options" [ngFlowchartCallbacks]="callbacks" [disabled]="disabled" (editCustomStepEvent)="onEdit($event)"></div>

**Comment by donbwhite** [comment]
@saurabhmehta-me did you figure this out? I've run into the same type of issue.

**Comment by michaelmarcuccio** [comment]
I can add a new event to the outputs:
```
 /**
 * Called after a step is initialized
 */
afterStepInit?: (step: NgFlowchartStepComponent) => void;
```

In custom-step.component.ts:
```
@Output() clicked = new EventEmitter();
```


In app.component.ts hosting the canvas:
```
stepSubscriptions: { stepId: string; sub: Subscription }[] = [];

afterDeleteStep(step) {
  this.stepSubscriptions.find(s => s.stepId === step.id)?.sub.unsubscribe();
}

afterStepInit(step) {
  // choose step type to register events for
  if (step.type === 'router') {
    this.stepSubscriptions.push({
      stepId: step.id,
      sub: (step as CustomStepComponent).clicked.subscribe(() => {
        console.log('clicked in parent');
      }),
    });
  }
}
```

if this works for you guys or if anyone can think of a better way to do this just let me know and I can add it.

**Comment by michaelmarcuccio** [comment]
It would help if one of you could give a specific use case to why you need the event in the canvas hosting component instead of just handling the event in the step component. @saurabhmehta-me @donbwhite 

@joel-wenzel do you have any opinions on this solution? Seems a bit weird, but it works.
