### ISSUE TITLE
Symbolic node to route the flow back from child to parent

### ISSUE THREAD

**Issue by saurabhmehta-me** [joel-wenzel/ng-flowchart#44]
We have a use case where a child can route the flow to an existing parent. There should be an option to add a Symbolic Node that is shown as a child node but it represents a parent above in the call flow. The symbolic node should be clickable and it should vertically scroll to the parent when clicked on the symbolic node

**Comment by Rinkuu97** [comment]
@saurabhmehta-me  did you figure this out? I've run into the same type of issue.
