### ISSUE TITLE
Delete a particular step

### ISSUE THREAD

**Issue by ashutoshAgreeya** [joel-wenzel/ng-flowchart#46]
We are not allowed to delete a particular step, when I tried to delete the particular step, then all the children are getting deleted.

**Comment by Huascar321** [comment]
I assume you are using **this.destroy** method to delete your step.
That method accepts a parameter called recursive which can be true or false.
If true then your step will be deleted including all its childrens.
If false then only your step will be deleted but its children will not be affected.
`onDelete() {
    this.destroy(false);
  }`
