### ISSUE TITLE
Merge children

### ISSUE THREAD

**Issue by mikenlanggio** [joel-wenzel/ng-flowchart#47]
Is any way to merge two children to the next step?

**Comment by michaelmarcuccio** [comment]
Yes, you can put two steps into a nested flow like in the example.
[https://stackblitz.com/edit/ng-flowchart-nested?file=src%2Fapp%2Fnested-flow%2Fnested-flow.component.ts](https://stackblitz.com/edit/ng-flowchart-nested?file=src%2Fapp%2Fnested-flow%2Fnested-flow.component.ts)
