### ISSUE TITLE
Multiple parents

### ISSUE THREAD

**Issue by noaahh** [joel-wenzel/ng-flowchart#5]
Is it possible or is it planned that a step can have multiple parents? In other words, that several branches of steps lead back into one?

**Comment by joel-wenzel** [comment]
I would like to at some point but just don't have a lot of time to work on this project lately. I can look into the feasibility of it over the weekend.

**Comment by joel-wenzel** [comment]
@noaahh This is now supported by [nesting charts](https://stackblitz.com/edit/ng-flowchart-nested?file=src/app/nested-flow/nested-flow.component.ts) in version 1.0.0-beta.
I am going to update the documentation and clean up a few things in the coming days, namely around the sizing options of the nested charts

**Comment by noaahh** [comment]
Thanks a lot!
