### ISSUE TITLE
Multiple Canvas inside same project

### ISSUE THREAD

**Issue by GouthamHarshith1997** [joel-wenzel/ng-flowchart#54]
Is it possible to have two canvas in the same project? If yes may I know the repo link?

**Comment by michaelmarcuccio** [comment]
yes, [https://stackblitz.com/edit/ng-flowchart-nested-xdpfuw?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-flowchart-nested-xdpfuw?file=src%2Fapp%2Fapp.component.ts)
