### ISSUE TITLE
How to connect one or more than one child to any other node.

### ISSUE THREAD

**Issue by Rinku97** [joel-wenzel/ng-flowchart#58]
Can we add the feature to connect the two child node back to any other parent node or any other subsequent node??

How we can do that? That can give it a more flexibility. 

I have attached a sample image for the reference. Please Check!

![FlowChart](https://user-images.githubusercontent.com/64198117/209303834-11555427-4842-4fce-9793-855e8efc2bbc.PNG)

**Comment by ranjeetranjan** [comment]
+1
