### ISSUE TITLE
Delete the function that allow to add parent steps (Above)

### ISSUE THREAD

**Issue by javierlopezg00** [joel-wenzel/ng-flowchart#59]
I have some issues when I put a new step like a parent for another step, so I want to deactivate the function that allow to put step above the step, I just need to add steps left, right and below but I don't know how to do it. 
I need that when the user try to put a parent, the system does not allow it. 

For the moment I just disable the above points that appear when we drag a new step, but still working if I drop the step like a parent, so I just found a visual solution but I need a functional solution.
Thanks for the help. <3

**Comment by michaelmarcuccio** [comment]
custom-step.component.ts
```
 // prevents you from dropping this step above other steps
  canDrop(dropEvent: NgFlowchart.DropTarget): boolean {
    return !dropEvent || dropEvent.position !== 'ABOVE';
  }
  
  // prevents you from dropping other steps above this step type
  getDropPositionsForStep(
    pendingStep: NgFlowchart.PendingStep
  ): NgFlowchart.DropPosition[] {
    return ['LEFT', 'RIGHT', 'BELOW'];
  }
```
