### ISSUE TITLE
Option to define the properties  

### ISSUE THREAD

**Issue by ranjeetranjan** [joel-wenzel/ng-flowchart#63]
I just to check if we have any roadmap for implementing properties of any canvas or element as it be easy for the end user like its there in the [Alyssa X Flowy](https://github.com/alyssaxuu/flowy). 
Example
<img width="1439" alt="Screenshot 2023-01-15 at 3 39 37 PM" src="https://user-images.githubusercontent.com/9720690/212535056-76e929eb-e40b-4761-b8ee-0a8a93d8fcbd.png">

**Comment by michaelmarcuccio** [comment]
Yes this exists already. You use a custom step and the data property. [https://github.com/joel-wenzel/ng-flowchart#step-object-methods-and-properties](https://github.com/joel-wenzel/ng-flowchart#step-object-methods-and-properties)

**Comment by ranjeetranjan** [comment]
Great and Thanks
