### ISSUE TITLE
controlling connections

### ISSUE THREAD

**Issue by deniskkk** [joel-wenzel/ng-flowchart#73]
Is there a way to control if the connection is valid or no?
I have studied the code and wanted to override isValidConnectorDropTarget() this method, but its private (ng-flowchart-step.component and ng-flowchart.component). Can you make it protected or public?

**Comment by michaelmarcuccio** [comment]
I will add an extensibility point to this, not a direct override as there are some parts that should not be overridden like allowing the same connector to be created twice.
