### ISSUE TITLE
How can i manuaaly handle dropEvents?

### ISSUE THREAD

**Issue by fclmman** [joel-wenzel/ng-flowchart#79]
In some cases i would like manually manage the drop events, I would like to get info about the target and source steps, and manage it manually; for example add the droppped step as sibling or not according to my custom logic, or mabe cancel the drop, or perform some other actions; but could not find api for this in documentation

**Comment by michaelmarcuccio** [comment]
Use NgFlowchartStepComponent canDrop() and getDropPositionsForStep()
