### ISSUE TITLE
Two Way Binding for Custom Steps

### ISSUE THREAD

**Issue by hknsrr** [joel-wenzel/ng-flowchart#8]
Hi Joel,

For two way binding, it may be necessary to prefer in `this.data = {value: 'newValue'}` instead of using `this.data.value = 'newValue';`

```
<div class="step" #canvasContent>
  <span>{{ data.value }}</span>
  <input type="text" value="{{data.value}}" (input)="somethingChanged($event)">
  <button (click)="delete()">Delete</button>
</div>  
```

```
somethingChanged(e) {
    this.data = {
      value: e.target.value
    }
}
```

Thanks,

**Comment by joel-wenzel** [comment]
@hknsrr Yep. Data objects were passed directly to steps instead of being copied. Fixed in #9 and 1.0.1-beta version.
Updated [stackblitz](https://stackblitz.com/edit/ng-flowchart-form-binding?file=package.json) for your example.
Good find.
