### ISSUE TITLE
same View not Show after clone project

### ISSUE THREAD

**Issue by Bhavesh-07** [joel-wenzel/ng-flowchart#83]
![image](https://github.com/joel-wenzel/ng-flowchart/assets/63705370/df2275a9-28d3-42b2-8c3d-0fdad973e1bb)

**Comment by michaelmarcuccio** [comment]
That is from a demo app not part of this repo.

**Comment by Bhavesh-07** [comment]
Hello joel

Thanks for Quick Replay. I will need context menu options and export diagram options. So Any Way to get that functionality.

Thanks


Bhavesh Prajapati
---------------------------------- 
CONFIDOSOFT SOLUTIONS PVT. LTD. 








---- On Thu, 24 Aug 2023 12:54:53 +0530 Michael Marcuccio ***@***.***> wrote ---





That is from a demo app not part of this repo.
