### ISSUE TITLE
Context Menu not show after clone project

### ISSUE THREAD

**Issue by Bhavesh-07** [joel-wenzel/ng-flowchart#84]
Context Menu options not show me after clone project and how to export diagram as image

**Comment by michaelmarcuccio** [comment]
Those must be custom implementations.

**Comment by Bhavesh-07** [comment]
is it possible to Provide me this dots menu code
![image](https://github.com/joel-wenzel/ng-flowchart/assets/63705370/503e712b-c9ff-4e4a-b926-5ee0af274e07)
