### ISSUE TITLE
Positioning bugs out on changing size of steps. 

### ISSUE THREAD

**Issue by mostafahassaan** [joel-wenzel/ng-flowchart#89]
I'm having this issue that i would greatly appreciate some help with. 
I'm using a custom step extending NgFlowchartStepComponent, the component looks as so to start with
<img width="264" alt="Screenshot 2023-10-05 121559" src="https://github.com/joel-wenzel/ng-flowchart/assets/3532971/56308c98-aade-4504-a466-15469eecd98c">
After adding some elements to said component it resizes to fill these elements. However it's positioning gets misaligned as so
<img width="298" alt="Screenshot 2023-10-05 121709" src="https://github.com/joel-wenzel/ng-flowchart/assets/3532971/c41bab1e-68c1-4e76-ba4d-544fb4de8329">
Moving the step fixes alignment.
<img width="271" alt="Screenshot 2023-10-05 121735" src="https://github.com/joel-wenzel/ng-flowchart/assets/3532971/243470b8-661c-4c3c-bb97-b3197052f75c">

I've tried calling reRender on canvas when the size changes however i can not seem to fix it. 
How can I fix this without moving the step?

**Comment by michaelmarcuccio** [comment]
Not that it helps you resolve the problem, but this has always been an issue. Without some sort of fix, it is recommended to keep your steps the same size once rendered.

**Comment by mostafahassaan** [comment]
Understood. However, a call to NgFlowchartCanvasDirective.getFlow().render() re-renders the page correctly. Is it not possible to detect step size changes?
