### ISSUE TITLE
Possibility to connect multiple parents to a child

### ISSUE THREAD

**Issue by Wolfskii** [joel-wenzel/ng-flowchart#90]
I wonder if it would be possible to implement an option to be able to connect multiple parents into the same child somehow?

**Comment by jmoratat** [comment]
Same needed here!! This feature would be fantastic!

**Comment by michaelmarcuccio** [comment]
This feature exists using ```NgFlowchart.Options.manualConnectors = true``` to draw arrows from parents to a single child.
