### ISSUE TITLE
Angular 17 support - cannot drop steps on empty canvas

### ISSUE THREAD

**Issue by woojto** [joel-wenzel/ng-flowchart#93]
Please add compatibility to Angular 17. After upgrading project from Angular 16 to 17, we no longer can drop steps onto empty canvas which is a breaking issue.

**Comment by eugenedw** [comment]
+1, not working in NG17 using the most basic configuration (outlined in Wiki), can't drop to canvas

HTML
```
<div class="palette">
  <div class="palette-item" *ngFor="let item of items" 
       [ngFlowchartStep]="{ template: stepContent, type: item.type, data: item.data }">
    <span>Item {{item.name}}</span>
  </div>
</div>
<ng-template #stepContent>
  <div class="step-container">
    <div class="step-heading">
      heading
    </div>
    <div class="step-content">
      content
    </div>
  </div>
</ng-template>
<div class="canvas-wrap">
  <div class="goal-canvas" ngFlowchartCanvas></div>
</div>
```

CSS
```
.canvas-wrap {
  min-height: 400px;
  display: flex;
  background-color: #000;
}

.goal-canvas {
  position: relative;
  flex-grow: 1;
  background-size: 30px 30px;
  background-image: linear-gradient(90deg, #343434 1px, transparent 0), linear-gradient(180deg, #343434 1px, transparent 0);
}

.palette-item {
  width: 250px;
  height: 40px;
  border: solid 2px #334799;
}
```

TS
```
@NgModule({
  declarations: [
    MyCustomComponent
  ],
  imports: [
    NgFlowchartModule
  ],
  exports: [
    MyCustomComponent
  ]
})
export class MyCustomAppModule{ }
...

@Component({
  selector: 'app-my-custom-component',
  templateUrl: './my-custom-component.html',
  styleUrl: './my-custom-component.scss'
})
export class MyCustomComponent {
      items = [
          {
            name: 'Logger',
            type: 'log',
            data: {
              name: 'Log',
              icon: { name: 'log-icon', color: 'blue' },
              config: {
                message: null,
                severity: null
              }
            }
          }
        ]
}
```

**Comment by thiagopg84** [comment]
Any news on this? 🥲 We also need NG17 support since it will become the latest LTS version in a few days.

**Comment by mtzea** [comment]
I've probably found the solution. At least it works for me on v17 project.
In the [ng-flowchart-canvas.directive.ts](https://github.com/joel-wenzel/ng-flowchart/blob/0f53770fbb0fee818ecf94d8221130fef69297d9/projects/ng-flowchart/src/lib/ng-flowchart-canvas.directive.ts#L38) file I've replaced lines 38-40 with the following code:
```
let closestCanvasId = event.target.closest('.ngflowchart-canvas-content')?.id;
if (closestCanvasId === undefined) {
  closestCanvasId = event.target.closest('div').querySelector('.ngflowchart-canvas-content')?.id;
}
```
I know it probably could have been done better but at least it works in my use case. It would be great if somebody smarter than me checked it out.

**Comment by michaelmarcuccio** [comment]
Angular 17+ note: Requires use of { provide: REMOVE_STYLES_ON_COMPONENT_DESTROY, useValue: false } OR @import '@joelwenzel/ng-flowchart/assets/styles.scss'; to apply base step styles as Angular breaks base Component style inheritance with the new default REMOVE_STYLES_ON_COMPONENT_DESTROY: true
