### ISSUE TITLE
Angular v17 and v18 compatibility 

### ISSUE THREAD

**Issue by mtzea** [joel-wenzel/ng-flowchart#95]
Can we expect the library to be adapted for Angular v17 and v18?

Since the latest version that is fully compatible with the library - v16 - will have its LTS ended in the autumn, it seems reasonable to adapt the library to v17 and the recently released v18.

Compatibility with version v17 is already the subject of issue #93

**Comment by thiagopg84** [comment]
+1 🥲

**Comment by igino-dedomenico** [comment]
+1

**Comment by michaelmarcuccio** [comment]
Angular 17+ note: Requires use of { provide: REMOVE_STYLES_ON_COMPONENT_DESTROY, useValue: false } OR @import '@joelwenzel/ng-flowchart/assets/styles.scss'; to apply base step styles as Angular breaks base Component style inheritance with the new default REMOVE_STYLES_ON_COMPONENT_DESTROY: true
